### ISSUE TITLE
Inconsistent or manipulated run loot

### ISSUE THREAD

**Issue by msogrin** [molbal/abyss-tracker#4] opened 2020-02-23 18:31 UTC
https://abyss.eve-nt.uk/run/2868

This run was posted to the abyssal ingame channel "look at this jackpot run".

However, the total doesn't end up when looking at individual loot items. So either there's an error in calculation or display somewhere, or this submission was somehow manipulated and not validated by the app.

**Comment by molbal** [comment] 2020-02-23 18:53
Hi,

There is a bug in the loot value calculation somewhere. I have not yet found it. The bug seems to increase the looted isk by 25 to 100% - it might be an inconsistency because the loot value comes from Evepraisal directly and the individual item prices are cached for 24 hours - still such a big change is unlikely within 24 hours so I will further investigate.

Cheers

**Comment by molbal** [comment] 2020-02-29 22:00
Hi,

The bug is now fixed in v 1.3.4 

It was caused by Evepraisal returning buy order prices for blueprints, see this one for example: https://evepraisal.com/a/pgayz/zukdp36qoufkp8w9

It was factored in during calculating loot value, but now blueprint values are ignored.

Cheers

**Closed by molbal** 2020-02-29 22:00 UTC
Labels: bug
