### ISSUE TITLE
Fit profitability stats not updating

### ISSUE THREAD

**Issue by roastduckie** [molbal/abyss-tracker#104] opened 2021-06-22 18:37 UTC
**Describe the bug**
The profitability and break even statistics for my fit, #5192, have not updated properly. I did shakedown runs in T0 runs then moved to T1, but the tracker still reflects the stats from T0. Currently 6 T0 Gamma runs are taking priority over 58 T1 Exotic runs

I've attached screenshots of the website display and my own calculations.

I know from discord that the website's displayed value is cached, but perhaps the cache is not being updated properly? Or it is but it's not being displayed properly?

![image](https://user-images.githubusercontent.com/68725644/122981103-04c05700-d35f-11eb-87e8-dddd79be78f1.png)
Profitability of 6 T0 Gamma runs

![image](https://user-images.githubusercontent.com/68725644/122981132-0a1da180-d35f-11eb-9bca-007aafc0a726.png)
Profitability of 56 T1 Exotic runs

**Comment by molbal** [comment] 2021-08-07 18:11
Hey,

It's fixed now - it was caused by an incorrect query that thought 0 is a higher tier, than 1.

![kép](https://user-images.githubusercontent.com/5754480/128610067-953b74af-f24d-4e5e-9a00-3021251eb314.png)


Thanks for the report,
Veetor

**Closed by molbal** 2021-08-07 18:11 UTC
Labels: bug, fits
