### ISSUE TITLE
Stopwatch not working

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#15] opened 2020-05-09 19:01 UTC
Hi,

currently, the automatic stopwatch does not seem to pick up when you enter Abyssal space and just keeps on waiting.
I have observed this behavior since May 6th. Can you check whether this is an ESI problem or with the tracker?

A colleague of mine has the same problem, so I'm pretty sure it's not account-specific to me.

Best Regards,
Salvoxias

**Comment by molbal** [comment] 2020-05-09 19:07
Hi,

The current DDOS affects ESI and the location endpoint simply does not return anything. 

```
Return value of App\Connector\EveAPI\Location\LocationService::getCurrentLocation() must be an instance of stdClass, null returned
```

Let's hope it gets fixed soon, until then it sometimes works sometimes does not

Best regards,
Balint

**Comment by Salvoxia** [comment] 2020-05-09 19:08
Ah okay, I guess that makes sense as a damage mitigation in order to lower load. 
Thanks for the info!

**Comment by Salvoxia** [comment] 2020-05-22 17:43
I need to follow up on this.
The stopwatch has been working again for quite some time, but during the last days I encountered a strange issue every couple of runs. The stopwatch would initialize properly after loading the "Add Run" page, and the label would be yellow and say "Waiting to enter the Abyss".
But when I actually jumped in, it changed to red, saying "Ready to start stopwatch", and it would not start until stopped and re-started manually.
Any idea how this can happen?

![firefox_2020-05-22_19-15-39](https://user-images.githubusercontent.com/6501566/82694955-7877c800-9c64-11ea-8ef9-c54591cb50cf.png)

**Comment by molbal** [comment] 2020-09-23 22:05
Its fixed now - the problem was caused by the tracker caching the token expire time incorrectly, and this resulted in it trying to get the location with an expired token. This returned nothing therefore the stopwatch crashed in the background.

**Closed by molbal** 2020-09-23 22:05 UTC
Labels: bug
