### ISSUE TITLE
Timestamp below fit description randomly updates

### ISSUE THREAD

**Issue by zmsMarc** [molbal/abyss-tracker#78] opened 2021-01-18 09:22 UTC
**Describe the bug**
The Timestamp on a fit seems to update at random times, even if the fit wasnt edited by the author.
example: https://abyss.eve-nt.uk/fit/988

**To Reproduce**
I havent edited this fit since creation a few months ago. When I open or reload the page (not all the time) the timestamp seems to update:

![image](https://user-images.githubusercontent.com/9104198/104895966-d0430c00-5976-11eb-99d3-d6618f8e771f.png)
![image](https://user-images.githubusercontent.com/9104198/104895980-d638ed00-5976-11eb-86c8-165ed2d9eb83.png)

**Expected behavior**
Timestamp indicates the last change

**Comment by molbal** [comment] 2021-01-19 08:37
Hey,

This is caused by the timestamp automatically updating on the fits table - this is unintentional. 
The fit's total cost regularly updates based on individual items' price - this is intentional.

Until I find a way to restore the original timestamps, I am not scheduling a fix for this bug :(

**Comment by molbal** [comment] 2021-06-06 18:34
timestamp removed entirely!

**Closed by molbal** 2021-06-06 18:34 UTC
Labels: bug
